<?php

use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colegios = [
        	['Concepción', 'Hualpén', 'Centro Integral de Educación High Scope', 1],
        	['Concepción', 'Lota', 'Colegio Adventista De Lota', 2],
        	['Concepción', 'SanPaz', 'Colegio Alemán de Concepción', 2],
        	['Concepción', 'Concepción', 'Colegio Alerce', -1],
        	['Concepción', 'SanPaz', 'Colegio Almondale', 2],
        	['Concepción', 'Talcahuano', 'Colegio Amanecer Talcahuano', 1],
        	['Concepción', 'Los Ángeles', 'Colegio Beato Damián de Molokai', 2],
        	['Concepción', 'Talcahuano', 'Colegio Buena Vista F-493', 2],
        	['Concepción', 'Concepción', 'Colegio Carmela Romero De Espinosa', 2],
        	['Concepción', 'Chiguayante', 'Colegio Chileno Árabe', 2],
        	['Concepción', 'Yungay', 'Colegio Cholguan', 2],
        	['Concepción', 'Chiguayante', 'Colegio Concepción Chiguayante', 1],
        	['Concepción', 'SanPaz', 'Colegio Concepción San Pedro', 1],
        	['Concepción', 'Concepción', 'Colegio Creación', 2],
        	['Concepción', 'Penco', 'Colegio El Refugio', 1],
        	['Concepción', 'Talcahuano', 'Colegio Espiritu Santo', 2],
        	['Concepción', 'SanPaz', 'Colegio Fraternidad', -1],
        	['Concepción', 'SanPaz', 'Colegio Galvarino', -1],
        	['Concepción', 'Hualpén', 'Colegio Gran Bretaña', 2],
        	['Concepción', 'Los Ángeles', 'Colegio Ingles Woodland', 2],
        	['Concepción', 'Concepción', 'Colegio Inmaculada de Concepción', 2],
        	['Concepción', 'Concepción', 'Colegio Kingston College', 1],
        	['Concepción', 'Talcahuano', 'Colegio Los Condores D - 508', 2],
        	['Concepción', 'SanPaz', 'Colegio Los Educadores', 2],
        	['Concepción', 'Chiguayante', 'Colegio Madre Paulina ', 2],
        	['Concepción', 'Concepción', 'Colegio Metodista Concepción', 2],
        	['Concepción', 'Hualpén', 'Colegio Montaner', 2],
        	['Concepción', 'Concepción', 'Colegio República Del Brasil', -1],
        	['Concepción', 'Hualpén', 'Colegio Rucalhue', 2],
        	['Concepción', 'Concepción', 'Colegio Salesiano Concepción', 2],
        	['Concepción', 'Concepción', 'Colegio San Agustín', 2],
        	['Concepción', 'SanPaz', 'Colegio San Ignacio, Concepción', 1],
        	['Concepción', 'Nacimiento', 'Colegio San Juan de Dios', -1],
        	['Concepción', 'Coronel', 'Colegio San Pedro ', 2],
        	['Concepción', 'Talcahuano', 'Colegio Santa Bernardita', 2],
        	['Concepción', 'Concepción', 'Colegio Tecnico Profesional Los Acacios', 2],
        	['Concepción', 'Nacimiento', 'Colegio Teresiano Padre Enrique', 2],
        	['Concepción', 'Lota', 'Escuela Baldomero Lillo Figueroa', -1],
        	['Concepción', 'Talca ', 'Escuela Básica Talca', 2],
        	['Concepción', 'Talcahuano', 'Escuela Diego Portales', 2],
        	['Concepción', 'Cabrero', 'Escuela Enrique Zañartu Prieto.', 2],
        	['Concepción', 'Concepción', 'Escuela Esther Hunneus De Claro E-547', 2],
        	['Concepción', 'Arauco', 'Escuela F-743 San Pedro De Laraquete', 2],
        	['Concepción', 'Chiguayante', 'Escuela John F. Kennedy D-561', -1],
        	['Concepción', 'Quillón', 'Escuela Laguna Avendaño', 2],
        	['Concepción', 'Hualqui', 'Escuela Manuel Amat y Juniet D-600', 2],
        	['Concepción', 'Nacimiento', 'Escuela Nacimiento de Nuesto Señor', -1],
        	['Concepción', 'Hualqui', 'Escuela Nueva República', 1],
        	['Concepción', 'SanPaz', 'Escuela Particular Pedro De Oña', 2],
        	['Concepción', 'Coronel', 'Liceo Bicentenario Coronel', -1],
        	['Concepción', 'Concepción', 'Liceo Enrique Molina Garmendia', 2],
        	['Concepción', 'Hualpén', 'Liceo Industrial De La Construcción Hernan Valenzuela Leyton', 2],
        	['Concepción', 'Talcahuano', 'Liceo La Asuncion', -1],
        	['Concepción', 'Mulchen', 'Liceo Nuevo Mundo', 2],
        	['Concepción', 'Cañete', 'Liceo Politécnico Cañete', 2],
        	['Concepción', 'Arauco', 'Liceo Politecnico Carampangue', 2],
        	['Concepción', 'Trehuaco', 'Liceo Polivalente República Del Paraguay', -1],
        	['Concepción', 'Talcahuano', 'Liceo Santa Leonor', 1],
        	['Concepción', 'Talcahuano', 'Liceo Técnico C-25', 2],
        	['Concepción', 'Concepción', 'Liceo Técnico Profesional La Araucana', -1],
        	['Concepción', 'Tomé', 'Liceo Vicente Palacios Valdes', 2],
        	['Concepción', 'Concepción', 'Lycee Charles De Gaulle', 2],
        	['Concepción', 'Chiguayante', 'The Pacific School', 2],
        	['Concepción', 'Los Álamos', 'Zaida Araneda Vigueras', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Altas Cumbres', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Arriarán Barros', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Bosquemar', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Católico Beato Federico Ozanam', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Chileno Norteamericano', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Domingo Santa Maria', 2],
        	['Puerto Montt', 'Puerto Varas', 'Colegio Germania del Verbo Divino', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Inmaculada Concepción', 2],
        	['Puerto Montt', 'Frutillar', 'Colegio Kopernikus', 2],
        	['Puerto Montt', 'Frutillar', 'Colegio Madre De Dios', 2],
        	['Puerto Montt', 'Puerto Varas', 'Colegio Mirador del Lago', -1],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Nuevo horizonte', -1],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Paideia', 2],
        	['Puerto Montt', 'Purranque', 'Colegio Preciosa Sangre ', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Pumahue', 2],
        	['Puerto Montt', 'Los Muermos', 'Colegio Ramón Ángel Jara', 2],
        	['Puerto Montt', 'Puerto Varas', 'Colegio Rosita Novaro', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Salesiano Padre José Fernandez Pérez', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio San Francisco Javier', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio San Javier', 1],
        	['Puerto Montt', 'Puerto Montt', 'Colegio San José', -1],
        	['Puerto Montt', 'Calbuco', 'Colegio San Miguel', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Santo Tomás', 2],
        	['Puerto Montt', 'Frutillar', 'Escuela Bernardo Philippi', 2],
        	['Puerto Montt', 'Puerto Montt', 'Escuela Cayenel', 2],
        	['Puerto Montt', 'Puerto Montt', 'Escuela Hospitaliaria Puerto Montt', 2],
        	['Puerto Montt', 'Puerto Montt', 'Escuela Kimun Lawal Alerce', 2],
        	['Puerto Montt', 'Los Muermos', 'Escuela N° 213 El Laurel', 2],
        	['Puerto Montt', 'Puerto Montt', 'Escuela Nueva Alerce', 2],
        	['Puerto Montt', 'Llanquihue', 'Escuela Nueva Panitao', 2],
        	['Puerto Montt', 'Puerto Montt', 'Escuela Padre Hurtado', 2],
        	['Puerto Montt', 'Frutillar', 'Escuela Rural Los Linares de Casma', 2],
        	['Puerto Montt', 'Fresia', 'Escuela Rural San Andrés', 2],
        	['Puerto Montt', 'Fresia', 'Escuela San Andres de Tegualda', 2],
        	['Puerto Montt', 'Frutillar', 'Green College', -1],
        	['Puerto Montt', 'Puerto Montt', 'Instituto Alemán De Puerto Montt', 2],
        	['Puerto Montt', 'Purranque', 'Instituto Alemán De Purranque', 2],
        	['Puerto Montt', 'Puerto Montt', 'Instituto del Pacifico', 2],
        	['Puerto Montt', 'Puerto Montt', 'Lafquen Montessori', 2],
        	['Puerto Montt', 'Puerto Montt', 'Leonardo Da Vinci School', 2],
        	['Puerto Montt', 'Ancud', 'Liceo Bicentenario Ancud', 2],
        	['Puerto Montt', 'Osorno', 'Liceo Carmela Carvajal de Prat', 2],
        	['Puerto Montt', 'Puerto Montt', 'Liceo de hombres', 2],
        	['Puerto Montt', 'Puerto Montt', 'Liceo de Hombres Manuel Montt', 2],
        	['Puerto Montt', 'Puerto Montt', 'Liceo industrial Puerto Montt', 2],
        	['Puerto Montt', 'Puerto Montt', 'Liceo Manuel Montt', 1],
        	['Puerto Montt', 'Quellón', 'Liceo Paulo Freire', 2],
        	['Puerto Montt', 'Puerto Montt', 'Liceo Politécnico Mirasol', 2],
        	['Puerto Montt', 'Puerto Montt', 'Patagonia College', 2],
        	['Puerto Montt', 'Puerto Montt', 'Colegio Sagrada Familia', 2],
        	['Puerto Montt', 'Llanquihue', 'Saint Paul College', 2],
        	['Puerto Montt', 'Puerto Montt', 'The American School', 2],
        	['Santiago', 'Huechuraba', 'Boston College', -1],
        	['Santiago', 'Puente Alto', 'Centro Educacional Compañia De María Puente Alto', 2],
        	['Santiago', 'Isla De Maipo', 'Centro Educacional Isla De Maipo', -1],
        	['Santiago', 'La Florida', 'Colegio Achiga De La Comeduc', 2],
        	['Santiago', 'San Ramón', 'Colegio Alberto Blest Gana', -1],
        	['Santiago', 'Ñuñoa', 'Colegio Alexander Fleming', 2],
        	['Santiago', 'La Florida', 'Colegio Alicante de la Florida', 2],
        	['Santiago', 'Puente Alto', 'Colegio Alicante Ester', 2],
        	['Santiago', 'Santiago Centro', 'Colegio Alonso De Ercilla', 2],
        	['Santiago', 'Peñaflor', 'Colegio American School', 2],
        	['Santiago', 'La Florida', 'Colegio Antilhue', 2],
        	['Santiago', 'San Ramón', 'Colegio Artístico Habit - Art', 1],
        	['Santiago', 'San Miguel', 'Colegio Chile', 2],
        	['Santiago', 'Las Condes', 'Colegio Compañía de María Apoquindo', 2],
        	['Santiago', 'La Reina', 'Colegio Coronel Eleuterio Ramírez Molina ', 2],
        	['Santiago', 'La Reina', 'Colegio De La Salle', 1],
        	['Santiago', 'Puente Alto', 'Colegio Elisa Valdes', 2],
        	['Santiago', 'Talagante', 'Colegio Estrella de Belén', 2],
        	['Santiago', 'Santiago Centro', 'Colegio Excelsior', -1],
        	['Santiago', 'Peñalolen', 'Colegio Francisco de Miranda', 2],
        	['Santiago', 'El Bosque', 'Colegio General Alberto Bachelet', 2],
        	['Santiago', 'Rancagua', 'Colegio Inglés Saint John', 2],
        	['Santiago', 'Pedro Aguirre Cerda', 'Colegio José Agustín Alfonso', -1],
        	['Santiago', 'Providencia', 'Colegio Josefino Santísima Trinidad', 2],
        	['Santiago', 'Ñuñoa', 'Colegio Lenka Franulic', 2],
        	['Santiago', 'Puente Alto', 'Colegio Manquecura Ciudad Del Este', 2],
        	['Santiago', 'Providencia', 'Colegio María Inmaculada', 2],
        	['Santiago', 'Quinta Normal', 'Colegio Marquel', 2],
        	['Santiago', 'Puente Alto', 'Colegio Monte Olivo de Puente Alto', -1],
        	['Santiago', 'San Bernardo', 'Colegio Nobel Gabriela Mistral', 1],
        	['Santiago', 'Puente Alto', 'Colegio Nueva Era Siglo XXI', 2],
        	['Santiago', 'Santiago Centro', 'Colegio Ozanam', -1],
        	['Santiago', 'Quilicura', 'Colegio Palmarés', 2],
        	['Santiago', 'San Miguel', 'Colegio Parroquial de San Miguel', 2],
        	['Santiago', 'Peñaflor', 'Colegio Patrona De Lourdes', 2],
        	['Santiago', 'La Florida', 'Colegio Playground', 2],
        	['Santiago', 'Providencia', 'Colegio Providencia', -1],
        	['Santiago', 'Peñalolen', 'Colegio Rudolf Steiner', -1],
        	['Santiago', 'Talagante', 'Colegio Sagrado Corazón de Talagante', 2],
        	['Santiago', 'Quilicura', 'Colegio San Carlos de Quilicura', 1],
        	['Santiago', 'Maipú', 'Colegio San Francisco de Sales', -1],
        	['Santiago', 'Paine', 'Colegio San Genaro', 2],
        	['Santiago', 'Santiago Centro', 'Colegio San Ignacio, Santiago', 2],
        	['Santiago', 'La Pintana', 'Colegio San José de la Familia', 2],
        	['Santiago', 'Quilicura', 'Colegio San Pedro', 1],
        	['Santiago', 'Santiago Centro', 'Colegio Santa Cruz', 2],
        	['Santiago', 'Puente Alto', 'Colegio Santa María de la Cordillera', 2],
        	['Santiago', 'San Bernardo', 'Colegio Santa Teresa de San Bernardo', 2],
        	['Santiago', 'Estación Central', 'Colegio Sao Paulo', 2],
        	['Santiago', 'Providencia', 'Colegio Superior Cambridge', 2],
        	['Santiago', 'Puente Alto', 'Colegio Tacora', -1],
        	['Santiago', 'Quinta Normal', 'Corazon de Jesus', -1],
        	['Santiago', 'Puente Alto', 'Country School', 2],
        	['Santiago', 'Recoleta', 'Escuela Anne Eleonor Roosevelt', 2],
        	['Santiago', 'Quilicura', 'Escuela Básica El Mañio', 2],
        	['Santiago', 'La Reina', 'Escuela Básica Palestina', -1],
        	['Santiago', 'Santiago Centro', 'Escuela Básica Salvador Sanfuentes', 2],
        	['Santiago', 'Recoleta', 'Escuela Bilingue República del Paraguay', -1],
        	['Santiago', 'La Pintana', 'Escuela Celestin Freinet', -1],
        	['Santiago', 'Santiago Centro', 'Escuela Guillermo Matta', 2],
        	['Santiago', 'Renca', 'Escuela Jorge Alessandri Rodríguez ', 2],
        	['Santiago', 'Estación Central', 'Escuela Unión Latinoamericana', 2],
        	['Santiago', 'El Bosque', 'Escuela y Liceo Liahona', 2],
        	['Santiago', 'Renca', 'Fundacion San Vicente de Paul Colegio San Jose de Renca', 2],
        	['Santiago', 'Santiago Centro', 'Instituto Claudio Matte', -1],
        	['Santiago', 'Providencia', 'Instituto de Humanidades Luis Campino', 2],
        	['Santiago', 'Santiago Centro', 'Instituto Nacional José Miguel Carrera', 1],
        	['Santiago', 'Quinta Normal', 'Internado Nacional Barros Arana', 1],
        	['Santiago', 'Vitacura', 'Liceo Amanda Labarca', 2],
        	['Santiago', 'Providencia', 'Liceo Arturo Alessandri Palma', -1],
        	['Santiago', 'Maipú', 'Liceo Bicentenario De Niñas De Maipú', 2],
        	['Santiago', 'Talagante', 'Liceo Bicentenario Talagante', 2],
        	['Santiago', 'Macul', 'Liceo Camilo Ortuzar Montt', 2],
        	['Santiago', 'Ñuñoa', 'Liceo Carmela Silva Donoso ', 2],
        	['Santiago', 'La Cisterna', 'Liceo Electrotecnia Ramon Barros Luco', 2],
        	['Santiago', 'La Cisterna', 'Liceo Froilan Yañez De La Barra', 2],
        	['Santiago', 'San Bernardo', 'Liceo Lucila Godoy Alcayaga', -1],
        	['Santiago', 'Ñuñoa', 'Liceo Manuel de Salas', 2],
        	['Santiago', 'Santiago Centro', 'Liceo N°1 Javiera Carrera', -1],
        	['Santiago', 'San Bernardo', 'Liceo Nacional Bicentenario de Excelencia', 2],
        	['Santiago', 'Recoleta', 'Liceo Particular Avenida Recoleta', -1],
        	['Santiago', 'Renca', 'Liceo Politécnico Andes DUOC UC', 2],
        	['Santiago', 'Recoleta', 'Liceo Politecnico Juanita Fernande Solar', 2],
        	['Santiago', 'La Florida', 'Liceo Politecnico Vicente Valdes', 2],
        	['Santiago', 'Las Condes', 'Liceo Rafael Soto Mayor', 2],
        	['Santiago', 'Ñuñoa', 'Liceo República de Siria', -1],
        	['Santiago', 'Independencia', 'Liceo Rosa Ester Alessandri Rodriguez', 2],
        	['Santiago', 'Estación Central', 'Liceo Ruiz Tagle', 2],
        	['Santiago', 'Las Condes', 'Liceo Simón Bolivar', -1],
        	['Santiago', 'Maipú', 'Mater Purissima', 2],
        	['Santiago', 'Quilicura', 'Colegio Palmarés Oriente', -1],
        	['Santiago', 'Puente Alto', 'Liceo Polivante El Alborada', 2],
        	['Santiago', 'La Cisterna', 'Princess Anne School', 2],
        	['Santiago', 'San Miguel', 'Saint Patrick School', 2],
        	['Santiago', 'Las Condes', 'San Juan Evangelista', 2],
        	['Santiago', 'Ñuñoa', 'The Angel´s School', 2],
        	['Santiago', 'La Florida', 'Colegio Danes, particular Nº 922', 2],
        	['Santiago', 'Providencia', 'Colegio Josefino Santísima Trinidad', 2],
        	['Temuco', 'Collipulli', 'Benjamin Franklin E-103', 2],
        	['Temuco', 'Collipulli', 'Centro Educacional W.A. Mozart', 2],
        	['Temuco', 'Villarica', 'Colegio Alemán de Villarrica', -1],
        	['Temuco', 'Temuco', 'Colegio Augusto Winter', -1],
        	['Temuco', 'Temuco', 'Colegio Bautista', 2],
        	['Temuco', 'Temuco', 'Colegio Betania', 1],
        	['Temuco', 'Temuco', 'Colegio De Aplicación', 2],
        	['Temuco', 'Temuco', 'Colegio Franciscano De Temuco', 2],
        	['Temuco', 'Temuco', 'Colegio Hebreo', -1],
        	['Temuco', 'Angol', 'Colegio Hermanos Carrera', 1],
        	['Temuco', 'Villarica', 'Colegio Humanidades Villarica', 2],
        	['Temuco', 'Traiguén', 'Colegio Inglés Mi Mundo', 2],
        	['Temuco', 'Temuco', 'Colegio Innov-Arte', 2],
        	['Temuco', 'Traiguén', 'Colegio Louis Pasteur', 2],
        	['Temuco', 'Temuco', 'Colegio Montessori Millantú', 2],
        	['Temuco', 'Temuco', 'Colegio Nueva Concepción', 1],
        	['Temuco', 'Pucón', 'Colegio Pucón ', 2],
        	['Temuco', 'Temuco', 'Colegio San Francisco de Temuco', 2],
        	['Temuco', 'Victoria', 'Colegio Santa Cruz Victoria', 2],
        	['Temuco', 'Gorbea', 'Complejo Educacional Andrés Antonio Gorbea', 2],
        	['Temuco', 'Collipulli', 'Complejo Educacional Collipulli', 2],
        	['Temuco', 'Freire', 'Complejo Educacional Juan Schleyer ', -1],
        	['Temuco', 'Temuco', 'Complejo Educacional La Frontera ', -1],
        	['Temuco', 'Vilcún', 'Complejo Educacional La Granja Cajon', 1],
        	['Temuco', 'Vilcún', 'Complejo Educacional Padre Nicolás', 2],
        	['Temuco', 'Temuco', 'Escuela Artística Armando Dufey Blanc', 2],
        	['Temuco', 'Loncoche', 'Escuela Básica Araucarias', 2],
        	['Temuco', 'Carehue', 'Escuela Básica De Nehuentue', -1],
        	['Temuco', 'Lonquimay', 'Escuela Básica Fronteriza', 2],
        	['Temuco', 'Gorbea', 'Escuela Cinco', 2],
        	['Temuco', 'Lautaro', 'Escuela Corazon de Jesus', 2],
        	['Temuco', 'Carehue', 'Escuela Docksta', 1],
        	['Temuco', 'Temuco', 'Escuela Emprender ', 1],
        	['Temuco', 'Temuco', 'Escuela Francia', -1],
        	['Temuco', 'Villarica', 'Escuela N°1 Sagrada Familia ', 2],
        	['Temuco', 'Cunco', 'Escuela Nº 7 La Dehesa', -1],
        	['Temuco', 'Pucón', 'Escuela Nuestra Señora de Fátima', 2],
        	['Temuco', 'Cautín', 'Escuela P -515 Ñirrimapu', 2],
        	['Temuco', 'Temuco', 'Escuela Particular Los Trigales 487', 1],
        	['Temuco', 'Lonquimay', 'Escuela Particular n°2, Lonquimay', 1],
        	['Temuco', 'Temuco', 'Escuela Rural Dr. Muhajir', -1],
        	['Temuco', 'Temuco', 'Escuela San Francisco Cunco Chico', 2],
        	['Temuco', 'Lautaro', 'Escuela Vallepenco', 2],
        	['Temuco', 'Temuco', 'Escuela Villa Carolina', -1],
        	['Temuco', 'Nueva Imperial', 'Fundación Colegio San Francisco de Asís ', 2],
        	['Temuco', 'Pitrufquen', 'Fundación Educacional Colegio Madres Domínicas', 2],
        	['Temuco', 'Temuco', 'George Chaytor English College', 1],
        	['Temuco', 'Temuco', 'Greenhouse School', 2],
        	['Temuco', 'Vilcún', 'Instituto Claret', 2],
        	['Temuco', 'Angol', 'Liceo Bicentenario Enrique Ballacey', 1],
        	['Temuco', 'Loncoche', 'Liceo Bicentenario Padre Alberto Hurtado Cruchaga', -1],
        	['Temuco', 'Temuco', 'Liceo Bicentenario Temuco', 2],
        	['Temuco', 'Temuco', 'Liceo Camilo Henríquez', 2],
        	['Temuco', 'Villarica', 'Liceo Ciencias y Humanidades', 2],
        	['Temuco', 'Temuco', 'Liceo Industrial Temuco', 2],
        	['Temuco', 'Cholchol', 'Liceo James Mundell', 2],
        	['Temuco', 'Temuco', 'Liceo Jan Comenius', -1],
        	['Temuco', 'Lautaro', 'Liceo Jorge Teillier Sandoval', 2],
        	['Temuco', 'Curacautín', 'Liceo Las Araucarias', 1],
        	['Temuco', 'Temuco', 'Liceo Pablo Neruda', 2],
        	['Temuco', 'Temuco', 'Liceo Politecnico Pueblo Nuevo', -1],
        	['Temuco', 'Temuco', 'Saint Patrick School', 2],
        	['Temuco', 'Freire', 'Escuela Santa Cruz De Freire', -1],
        	['Temuco', 'Temuco', 'Scole Creare', 2],
        	['Temuco', 'Pitrufquen', 'The Forest School', 2],
        	['Temuco', 'Temuco', 'Liceo Técnico Profesional Centenario', 2],
        	['Valparaíso', 'Viña Del Mar', 'Colegio Alemán de Valparaíso', 2],
        	['Valparaíso', 'Viña Del Mar', 'Colegio Capellan Pascal', 2],
        	['Valparaíso', 'Quilpué', 'Colegio CarloMagno', -1],
        	['Valparaíso', 'Valparaíso', 'Colegio Diego Velazquez', 2],
        	['Valparaíso', 'Casa Blanca', 'Colegio El Arrayan', 2],
        	['Valparaíso', 'Nogales', 'Colegio El Melón', -1],
        	['Valparaíso', 'Quilpué', 'Colegio Esperanza ', 2],
        	['Valparaíso', 'Quilpué', 'Colegio Ingles San Anfeli', 2],
        	['Valparaíso', 'Viña Del Mar', 'Colegio Inmaculada de Lourdes', 2],
        	['Valparaíso', 'Valparaíso', 'Colegio Jeanne D. Arc', -1],
        	['Valparaíso', 'Valparaíso', 'Colegio Leonardo Murialdo', 2],
        	['Valparaíso', 'Quilpué', 'Colegio Los Reyes', 2],
        	['Valparaíso', 'Viña Del Mar', 'Colegio Manantial', 2],
        	['Valparaíso', 'Valparaíso', 'Colegio Mar Abierto', 1],
        	['Valparaíso', 'Viña Del Mar', 'Colegio Montealegre', 2],
        	['Valparaíso', 'Concón', 'Colegio Montemar', 2],
        	['Valparaíso', 'Villa Alemana', 'Colegio Nacional Santa Ana', 2],
        	['Valparaíso', 'Villa Alemana', 'Colegio Nueva Esperanza', 2],
        	['Valparaíso', 'Villa Alemana', 'Colegio Nuevo Milenio', 2],
        	['Valparaíso', 'Valparaíso', 'Colegio Numancia', 2],
        	['Valparaíso', 'Zapallar', 'Colegio Parroquial Francisco Didier', 2],
        	['Valparaíso', 'Quilpué', 'Colegio Pasionistas de Quilpué', 2],
        	['Valparaíso', 'Valparaíso', 'Colegio Patricio Lynch', 2],
        	['Valparaíso', 'Marga Marga', 'Colegio Poeta Daniel De La Vega', 2],
        	['Valparaíso', 'Villa Alemana', 'Colegio Robles', 1],
        	['Valparaíso', 'Viña Del Mar', 'Colegio Ruben Castro Diurno', 2],
        	['Valparaíso', 'Viña Del Mar', 'Colegio Saint Dominic', 2],
        	['Valparaíso', 'Quilpué', 'Colegio Saint Lawrence', 2],
        	['Valparaíso', 'Valparaíso', 'Colegio Salesiano', 2],
        	['Valparaíso', 'Villa Alemana', 'Colegio San Agustin', 2],
        	['Valparaíso', 'Valparaíso', 'Colegio San Andres', 2],
        	['Valparaíso', 'Viña Del Mar', 'Colegio San Ignacio, Valparaíso', 2],
        	['Valparaíso', 'Los Andes', 'Colegio San Sebastían de Los Andes', -1],
        	['Valparaíso', 'Valparaíso', 'Colegio San Vicente', 2],
        	['Valparaíso', 'Valparaíso', 'Colegio Santa Clara de Placilla', 2],
        	['Valparaíso', 'Nogales', 'Colegio Santa Isabel', 2],
        	['Valparaíso', 'Valparaíso', 'Colegio Umbral de Curauma', 2],
        	['Valparaíso', 'Quillota', 'Colegio Valle del Aconcagua', 1],
        	['Valparaíso', 'Olmué', 'Escuela Atenas', 2],
        	['Valparaíso', 'Quillota', 'Escuela Básica Arauco', -1],
        	['Valparaíso', 'Llay-Llay', 'Escuela Básica El Porvenir', 1],
        	['Valparaíso', 'Olmué', 'Escuela Básica Lo Narvaez', -1],
        	['Valparaíso', 'Valparaíso', 'Escuela Casa Montessori Cerro Alegre', 2],
        	['Valparaíso', 'Viña Del Mar', 'Escuela Eduardo Lezana Pincheira', 2],
        	['Valparaíso', 'Llay-Llay', 'Escuela Herminia Ortega de Croxatto', 2],
        	['Valparaíso', 'Limache', 'Escuela Héroes De Chile', -1],
        	['Valparaíso', 'San Felipe', 'Escuela Industrial Guillermo Richards Cuevas', 2],
        	['Valparaíso', 'Casa Blanca', 'Escuela Lagunillas G-457', 2],
        	['Valparaíso', 'Valparaíso', 'Escuela Mariano Latorre', 2],
        	['Valparaíso', 'Zapallar', 'Escuela Mercedes Maturana Gallardo', 1],
        	['Valparaíso', 'San Antonio', 'Instituto Del Puerto', 2],
        	['Valparaíso', 'Viña Del Mar', 'Libertador Bernardo O\'Higgins Riquelme', -1],
        	['Valparaíso', 'Valparaíso', 'Liceo Bicentenario Valparaíso', 1],
        	['Valparaíso', 'Villa Alemana', 'Liceo Divina Maestra', 2],
        	['Valparaíso', 'Valparaíso', 'Liceo Eduardo De La Barra', -1],
        	['Valparaíso', 'La Calera', 'Liceo Industrial Oscar Corona Barahona', -1],
        	['Valparaíso', 'Viña Del Mar', 'LIceo José Cortés Brown Recreo', -1],
        	['Valparaíso', 'Nogales', 'Liceo Juan Rusque Portal', 2],
        	['Valparaíso', 'Nogales', 'Liceo Juana Ross de Edward', 1],
        	['Valparaíso', 'Viña Del Mar', 'Liceo Rene Descartes', 2],
        	['Valparaíso', 'Viña Del Mar', 'Liceo Santa Teresa de los Andes', 2],
        	['Valparaíso', 'Valparaíso', 'Liceo Técnico de Valparaiso', 2],
        	['Valparaíso', 'Viña Del Mar', 'Maria Auxiliadora Viña Del Mar', 1],
        	['Valparaíso', 'Viña Del Mar', 'Escuela Rubén Castro', 2],
        	['Valparaíso', 'Viña Del Mar', 'Saint Paul\'s School', 2],
        	['Valparaíso', 'Santo Domingo', 'Santo Domingo Country School', -1],
        	['Valparaíso', 'Valparaíso', 'Scuola Italiana Arturo Dell\' Oro', 2],
        	['Valparaíso', 'Valparaíso', 'Seminario San Rafael', 2],
        	['Valparaíso', 'Viña Del Mar', 'The Kingstown School', 2],
        	['Valparaíso', 'Concón', 'Colegio Internacional Sek Pacífico', 2],
        	['Valparaíso', 'Viña Del Mar', 'Colegio Winterhill', 2]
        ];

        $comunas = array(
        	'Arica' => 1,
        	'Camarones' => 2,
        	'Putre' => 3,
        	'General Lagos' => 4,
        	'Iquique' => 5,
        	'Alto Hospicio' => 6,
        	'Pozo Almonte' => 7,
        	'Camiña' => 8,
        	'Colchane' => 9,
        	'Huara' => 10,
        	'Pica' => 11,
        	'Antofagasta' => 12,
        	'Mejillones' => 13,
        	'Sierra Gorda' => 14,
        	'Taltal' => 15,
        	'Calama' => 16,
        	'Ollagüe' => 17,
        	'San Pedro de Atacama' => 18,
        	'Tocopilla' => 19,
        	'María Elena' => 20,
        	'Copiapó' => 21,
        	'Caldera' => 22,
        	'Tierra Amarilla' => 23,
        	'Chañaral' => 24,
        	'Diego de Almagro' => 25,
        	'Vallenar' => 26,
        	'Alto del Carmen' => 27,
        	'Freirina' => 28,
        	'Huasco' => 29,
        	'La Serena' => 30,
        	'Coquimbo' => 31,
        	'Andacollo' => 32,
        	'La Higuera' => 33,
        	'Paihuano' => 34,
        	'Vicuña' => 35,
        	'Illapel' => 36,
        	'Canela' => 37,
        	'Los Vilos' => 38,
        	'Salamanca' => 39,
        	'Ovalle' => 40,
        	'Combarbalá' => 41,
        	'Monte Patria' => 42,
        	'Punitaqui' => 43,
        	'Río Hurtado' => 44,
        	'Valparaíso' => 45,
        	'Casablanca' => 46,
        	'Concón' => 47,
        	'Juan Fernández' => 48,
        	'Puchuncaví' => 49,
        	'Quintero' => 50,
        	'Viña del Mar' => 51,
        	'Isla de Pascua' => 52,
        	'Los Andes' => 53,
        	'Calle Larga' => 54,
        	'Rinconada' => 55,
        	'San Esteban' => 56,
        	'La Ligua' => 57,
        	'Cabildo' => 58,
        	'Papudo' => 59,
        	'Petorca' => 60,
        	'Zapallar' => 61,
        	'Quillota' => 62,
        	'La Calera' => 63,
        	'Hijuelas' => 64,
        	'La Cruz' => 65,
        	'Nogales' => 66,
        	'San Antonio' => 67,
        	'Algarrobo' => 68,
        	'Cartagena' => 69,
        	'El Quisco' => 70,
        	'El Tabo' => 71,
        	'Santo Domingo' => 72,
        	'San Felipe' => 73,
        	'Catemu' => 74,
        	'Llaillay' => 75,
        	'Panquehue' => 76,
        	'Putaendo' => 77,
        	'Santa María' => 78,
        	'Quilpué' => 79,
        	'Limache' => 80,
        	'Olmué' => 81,
        	'Villa Alemana' => 82,
        	'Rancagua' => 83,
        	'Codegua' => 84,
        	'Coinco' => 85,
        	'Coltauco' => 86,
        	'Doñihue' => 87,
        	'Graneros' => 88,
        	'Las Cabras' => 89,
        	'Machalí' => 90,
        	'Malloa' => 91,
        	'Mostazal' => 92,
        	'Olivar' => 93,
        	'Peumo' => 94,
        	'Pichidegua' => 95,
        	'Quinta de Tilcoco' => 96,
        	'Rengo' => 97,
        	'Requínoa' => 98,
        	'San Vicente' => 99,
        	'Pichilemu' => 100,
        	'La Estrella' => 101,
        	'Litueche' => 102,
        	'Marchihue' => 103,
        	'Navidad' => 104,
        	'Paredones' => 105,
        	'San Fernando' => 106,
        	'Chépica' => 107,
        	'Chimbarongo' => 108,
        	'Lolol' => 109,
        	'Nancagua' => 110,
        	'Palmilla' => 111,
        	'Peralillo' => 112,
        	'Placilla' => 113,
        	'Pumanque' => 114,
        	'Santa Cruz' => 115,
        	'Talca' => 116,
        	'Constitución' => 117,
        	'Curepto' => 118,
        	'Empedrado' => 119,
        	'Maule' => 120,
        	'Pelarco' => 121,
        	'Pencahue' => 122,
        	'Río Claro' => 123,
        	'San Clemente' => 124,
        	'San Rafael' => 125,
        	'Cauquenes' => 126,
        	'Chanco' => 127,
        	'Pelluhue' => 128,
        	'Curicó' => 129,
        	'Hualañé' => 130,
        	'Licantén' => 131,
        	'Molina' => 132,
        	'Rauco' => 133,
        	'Romeral' => 134,
        	'Sagrada Familia' => 135,
        	'Teno' => 136,
        	'Vichuquén' => 137,
        	'Linares' => 138,
        	'Colbún' => 139,
        	'Longaví' => 140,
        	'Parral' => 141,
        	'Retiro' => 142,
        	'San Javier' => 143,
        	'Villa Alegre' => 144,
        	'Yerbas Buenas' => 145,
        	'Concepción' => 146,
        	'Coronel' => 147,
        	'Chiguayante' => 148,
        	'Florida' => 149,
        	'Hualqui' => 150,
        	'Lota' => 151,
        	'Penco' => 152,
        	'SanPaz' => 153,
        	'Santa Juana' => 154,
        	'Talcahuano' => 155,
        	'Tomé' => 156,
        	'Hualpén' => 157,
        	'Lebu' => 158,
        	'Arauco' => 159,
        	'Cañete' => 160,
        	'Contulmo' => 161,
        	'Curanilahue' => 162,
        	'Los Álamos' => 163,
        	'Tirúa' => 164,
        	'Los Ángeles' => 165,
        	'Antuco' => 166,
        	'Cabrero' => 167,
        	'Laja' => 168,
        	'Mulchén' => 169,
        	'Nacimiento' => 170,
        	'Negrete' => 171,
        	'Quilaco' => 172,
        	'Quilleco' => 173,
        	'San Rosendo' => 174,
        	'Santa Bárbara' => 175,
        	'Tucapel' => 176,
        	'Yumbel' => 177,
        	'Alto Biobío' => 178,
        	'Chillán' => 179,
        	'Bulnes' => 180,
        	'Cobquecura' => 181,
        	'Coelemu' => 182,
        	'Coihueco' => 183,
        	'Chillán Viejo' => 184,
        	'El Carmen' => 185,
        	'Ninhue' => 186,
        	'Ñiquén' => 187,
        	'Pemuco' => 188,
        	'Pinto' => 189,
        	'Portezuelo' => 190,
        	'Quillón' => 191,
        	'Quirihue' => 192,
        	'Ránquil' => 193,
        	'San Carlos' => 194,
        	'San Fabián' => 195,
        	'San Ignacio' => 196,
        	'San Nicolás' => 197,
        	'Treguaco' => 198,
        	'Yungay' => 199,
        	'Temuco' => 200,
        	'Carahue' => 201,
        	'Cunco' => 202,
        	'Curarrehue' => 203,
        	'Freire' => 204,
        	'Galvarino' => 205,
        	'Gorbea' => 206,
        	'Lautaro' => 207,
        	'Loncoche' => 208,
        	'Melipeuco' => 209,
        	'Nueva Imperial' => 210,
        	'Padre Las Casas' => 211,
        	'Perquenco' => 212,
        	'Pitrufquén' => 213,
        	'Pucón' => 214,
        	'Saavedra' => 215,
        	'Teodoro Schmidt' => 216,
        	'Toltén' => 217,
        	'Vilcún' => 218,
        	'Villarrica' => 219,
        	'Cholchol' => 220,
        	'Angol' => 221,
        	'Collipulli' => 222,
        	'Curacautín' => 223,
        	'Ercilla' => 224,
        	'Lonquimay' => 225,
        	'Los Sauces' => 226,
        	'Lumaco' => 227,
        	'Purén' => 228,
        	'Renaico' => 229,
        	'Traiguén' => 230,
        	'Victoria' => 231,
        	'Valdivia' => 232,
        	'Corral' => 233,
        	'Lanco' => 234,
        	'Los Lagos' => 235,
        	'Máfil' => 236,
        	'Mariquina' => 237,
        	'Paillaco' => 238,
        	'Panguipulli' => 239,
        	'La Unión' => 240,
        	'Futrono' => 241,
        	'Lago Ranco' => 242,
        	'Río Bueno' => 243,
        	'Puerto Montt' => 244,
        	'Calbuco' => 245,
        	'Cochamó' => 246,
        	'Fresia' => 247,
        	'Frutillar' => 248,
        	'Los Muermos' => 249,
        	'Llanquihue' => 250,
        	'Maullín' => 251,
        	'Puerto Varas' => 252,
        	'Castro' => 253,
        	'Ancud' => 254,
        	'Chonchi' => 255,
        	'Curaco de Vélez' => 256,
        	'Dalcahue' => 257,
        	'Puqueldón' => 258,
        	'Queilén' => 259,
        	'Quellón' => 260,
        	'Quemchi' => 261,
        	'Quinchao' => 262,
        	'Osorno' => 263,
        	'Puerto Octay' => 264,
        	'Purranque' => 265,
        	'Puyehue' => 266,
        	'Río Negro' => 267,
        	'San Juan de la Costa' => 268,
        	'San Pablo' => 269,
        	'Chaitén' => 270,
        	'Futaleufú' => 271,
        	'Hualaihué' => 272,
        	'Palena' => 273,
        	'Coyhaique' => 274,
        	'Lago Verde' => 275,
        	'Aysén' => 276,
        	'Cisnes' => 277,
        	'Guaitecas' => 278,
        	'Cochrane' => 279,
        	'O\'Higgins' => 280,
        	'Tortel' => 281,
        	'Chile Chico' => 282,
        	'Río Ibáñez' => 283,
        	'Punta Arenas' => 284,
        	'Laguna Blanca' => 285,
        	'Río Verde' => 286,
        	'San Gregorio' => 287,
        	'Cabo de Hornos' => 288,
        	'Antártica' => 289,
        	'Porvenir' => 290,
        	'Primavera' => 291,
        	'Timaukel' => 292,
        	'Natales' => 293,
        	'Torres del Paine' => 294,
        	'Santiago' => 295,
        	'Cerrillos' => 296,
        	'Cerro Navia' => 297,
        	'Conchalí' => 298,
        	'El Bosque' => 299,
        	'Estación Central' => 300,
        	'Huechuraba' => 301,
        	'Independencia' => 302,
        	'La Cisterna' => 303,
        	'La Florida' => 304,
        	'La Granja' => 305,
        	'La Pintana' => 306,
        	'La Reina' => 307,
        	'Las Condes' => 308,
        	'Lo Barnechea' => 309,
        	'Lo Espejo' => 310,
        	'Lo Prado' => 311,
        	'Macul' => 312,
        	'Maipú' => 313,
        	'Ñuñoa' => 314,
        	'Pedro Aguirre Cerda' => 315,
        	'Peñalolén' => 316,
        	'Providencia' => 317,
        	'Pudahuel' => 318,
        	'Quilicura' => 319,
        	'Quinta Normal' => 320,
        	'Recoleta' => 321,
        	'Renca' => 322,
        	'San Joaquín' => 323,
        	'San Miguel' => 324,
        	'San Ramón' => 325,
        	'Vitacura' => 326,
        	'Puente Alto' => 327,
        	'Pirque' => 328,
        	'San José de Maipo' => 329,
        	'Colina' => 330,
        	'Lampa' => 331,
        	'Til Til' => 332,
        	'San Bernardo' => 333,
        	'Buin' => 334,
        	'Calera de Tango' => 335,
        	'Paine' => 336,
        	'Melipilla' => 337,
        	'Alhué' => 338,
        	'Curacaví' => 339,
        	'María Pinto' => 340,
        	'San Pedro' => 341,
        	'Talagante' => 342,
        	'El Monte' => 343,
        	'Isla de Maipo' => 344,
        	'Padre Hurtado' => 345,
        	'Peñaflor' => 346,
        );

        $comunas2 = array(
            'Concepción' => 146,
            'Puerto Montt' => 244,
            'Santiago' => 295,
            'Temuco' => 200,
            'Valparaíso' => 45,
        );

        for ($i=0; $i < 351; $i++) { 
	        DB::table('courses')->insert([
	            'id' => $i+1,
	            'name' => $colegios[$i][2],
	            'score' => $colegios[$i][3],
	            'commune_id' => $comunas[$colegios[$i][0]],
	            'created_at' => date('Y-m-d H:i:s'),
	            'updated_at' => date('Y-m-d H:i:s'),
	        ]);
        }

    }
}
